/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Jugador;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import manejadores.JuegoControl;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Fer
 */
public class Juego extends javax.swing.JFrame {

    private JuegoControl control = new JuegoControl();

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jugarLabel = new javax.swing.JLabel();
        registradoLabel = new javax.swing.JLabel();
        nuevoLabel = new javax.swing.JLabel();
        rankingLabel = new javax.swing.JLabel();
        salirLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jugarLabel1 = new javax.swing.JLabel();
        play = new javax.swing.JPanel();
        nuevoJugador = new javax.swing.JPanel();
        uNInsert = new javax.swing.JLabel();
        uNInsert1 = new javax.swing.JLabel();
        registerUsername = new javax.swing.JTextField();
        registerPassword = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        selectHero = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jugadorRegistrado = new javax.swing.JPanel();
        uNInsert2 = new javax.swing.JLabel();
        registerUsername1 = new javax.swing.JTextField();
        uNInsert3 = new javax.swing.JLabel();
        registerPassword1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        ranking = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankArea = new javax.swing.JTextArea();
        instrucciones = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUPER BATTLE HEROES 2ND ANNIVERSARY GOLD EDITION WITH DLC");
        getContentPane().setLayout(new java.awt.CardLayout());

        menu.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Channel", 0, 18)); // NOI18N
        jLabel1.setText("Super Battle Heroes 2nd Anniversary Gold Edition with DLC");

        jugarLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jugarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarLabel.setText("Jugar");
        jugarLabel.setAlignmentX(400.0F);

        registradoLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        registradoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registradoLabel.setText("Jugador Registrado");
        registradoLabel.setAlignmentX(400.0F);
        registradoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registradoLabelMouseClicked(evt);
            }
        });

        nuevoLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        nuevoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setText("Nuevo Jugador");
        nuevoLabel.setAlignmentX(400.0F);
        nuevoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoLabelMouseClicked(evt);
            }
        });

        rankingLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        rankingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rankingLabel.setText("Ranking");
        rankingLabel.setAlignmentX(400.0F);
        rankingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankingLabelMouseClicked(evt);
            }
        });

        salirLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        salirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirLabel.setText("Salir");
        salirLabel.setAlignmentX(400.0F);
        salirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirLabelMouseClicked(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText(" ");
        welcomeLabel.setAlignmentX(400.0F);

        jugarLabel1.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jugarLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarLabel1.setText("Instrucciones");
        jugarLabel1.setAlignmentX(400.0F);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(welcomeLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugarLabel1)
                    .addComponent(nuevoLabel)
                    .addComponent(rankingLabel)
                    .addComponent(salirLabel)
                    .addComponent(registradoLabel)
                    .addComponent(jugarLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel)
                .addGap(41, 41, 41)
                .addComponent(jugarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jugarLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registradoLabel)
                .addGap(18, 18, 18)
                .addComponent(nuevoLabel)
                .addGap(18, 18, 18)
                .addComponent(rankingLabel)
                .addGap(18, 18, 18)
                .addComponent(salirLabel)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        getContentPane().add(menu, "card2");

        javax.swing.GroupLayout playLayout = new javax.swing.GroupLayout(play);
        play.setLayout(playLayout);
        playLayout.setHorizontalGroup(
            playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        playLayout.setVerticalGroup(
            playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(play, "card3");

        uNInsert.setFont(new java.awt.Font("Channel", 0, 14)); // NOI18N
        uNInsert.setText("Contraseña");

        uNInsert1.setFont(new java.awt.Font("Channel", 0, 14)); // NOI18N
        uNInsert1.setText("Nombre de Usuario");

        registerButton.setText("Registrar");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        limpiarButton.setText("Limpiar");
        limpiarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nuevoJugadorLayout = new javax.swing.GroupLayout(nuevoJugador);
        nuevoJugador.setLayout(nuevoJugadorLayout);
        nuevoJugadorLayout.setHorizontalGroup(
            nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoJugadorLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uNInsert)
                    .addComponent(uNInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(registerPassword))
                .addGap(320, 320, 320))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limpiarButton)
                .addGap(59, 59, 59)
                .addComponent(registerButton)
                .addGap(405, 405, 405))
        );
        nuevoJugadorLayout.setVerticalGroup(
            nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoJugadorLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uNInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(limpiarButton))
                .addContainerGap(355, Short.MAX_VALUE))
        );

        getContentPane().add(nuevoJugador, "card4");

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton1");

        jToggleButton3.setText("jToggleButton1");

        jToggleButton4.setText("jToggleButton1");

        javax.swing.GroupLayout selectHeroLayout = new javax.swing.GroupLayout(selectHero);
        selectHero.setLayout(selectHeroLayout);
        selectHeroLayout.setHorizontalGroup(
            selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectHeroLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(selectHeroLayout.createSequentialGroup()
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(427, Short.MAX_VALUE))
            .addGroup(selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectHeroLayout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(607, Short.MAX_VALUE)))
        );
        selectHeroLayout.setVerticalGroup(
            selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectHeroLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectHeroLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(417, Short.MAX_VALUE)))
        );

        getContentPane().add(selectHero, "card8");

        uNInsert2.setFont(new java.awt.Font("Channel", 0, 14)); // NOI18N
        uNInsert2.setText("Nombre de Usuario");

        uNInsert3.setFont(new java.awt.Font("Channel", 0, 14)); // NOI18N
        uNInsert3.setText("Contraseña");

        jButton1.setText("Limpiar");

        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jugadorRegistradoLayout = new javax.swing.GroupLayout(jugadorRegistrado);
        jugadorRegistrado.setLayout(jugadorRegistradoLayout);
        jugadorRegistradoLayout.setHorizontalGroup(
            jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jugadorRegistradoLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uNInsert3)
                    .addComponent(uNInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerUsername1)
                    .addComponent(registerPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(259, 259, 259))
            .addGroup(jugadorRegistradoLayout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jButton1)
                .addGap(70, 70, 70)
                .addComponent(login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jugadorRegistradoLayout.setVerticalGroup(
            jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jugadorRegistradoLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uNInsert3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(login))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        getContentPane().add(jugadorRegistrado, "card5");

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        rankArea.setColumns(20);
        rankArea.setRows(5);
        jScrollPane1.setViewportView(rankArea);

        javax.swing.GroupLayout rankingLayout = new javax.swing.GroupLayout(ranking);
        ranking.setLayout(rankingLayout);
        rankingLayout.setHorizontalGroup(
            rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rankingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(54, 54, 54))
            .addGroup(rankingLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        rankingLayout.setVerticalGroup(
            rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rankingLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(65, 65, 65))
        );

        getContentPane().add(ranking, "card7");

        javax.swing.GroupLayout instruccionesLayout = new javax.swing.GroupLayout(instrucciones);
        instrucciones.setLayout(instruccionesLayout);
        instruccionesLayout.setHorizontalGroup(
            instruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        instruccionesLayout.setVerticalGroup(
            instruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(instrucciones, "card6");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem1.setMnemonic('P');
        jMenuItem1.setText("Pantalla Completa");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registradoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registradoLabelMouseClicked
        // TODO add your handling code here:
        menu.setVisible(false);
        jugadorRegistrado.setVisible(true);
    }//GEN-LAST:event_registradoLabelMouseClicked


    private void nuevoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoLabelMouseClicked
        // TODO add your handling code here:
        menu.setVisible(false);
        nuevoJugador.setVisible(true);
    }//GEN-LAST:event_nuevoLabelMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
        int yesNoResponse = JOptionPane.showConfirmDialog(null, "Deseas registrarte?", "Confirmar", JOptionPane.YES_NO_OPTION
        );
        if (yesNoResponse == JOptionPane.YES_OPTION) {
            control.registerUser(registerUsername.getText(), registerPassword.getText());
            welcomeLabel.setText("Bienvenido " + registerUsername.getText());
            nuevoJugador.setVisible(false);
            menu.setVisible(true);
        } else {
            nuevoJugador.setVisible(false);
            menu.setVisible(true);
        }

    }//GEN-LAST:event_registerButtonMouseClicked

    private void limpiarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarButtonMouseClicked
        // TODO add your handling code here:
        registerUsername.setText("");
        registerPassword.setText("");
    }//GEN-LAST:event_limpiarButtonMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        int yesNoResponse = JOptionPane.showConfirmDialog(null, "Deseas iniciar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION
        );
        if (yesNoResponse == JOptionPane.YES_OPTION) {
            try {
                control.getRegisteredUser(registerUsername1.getText(), registerPassword1.getText());
            } catch (SQLException ex) {
                Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
            }
            welcomeLabel.setText("Bienvenido " + registerUsername.getText());
            nuevoJugador.setVisible(false);
            menu.setVisible(true);
        } else {
            nuevoJugador.setVisible(false);
            menu.setVisible(true);
        }
    }//GEN-LAST:event_loginMouseClicked

    private void rankingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankingLabelMouseClicked
        try {
            // TODO add your handling code here:
            menu.setVisible(false);
            ranking.setVisible(true);
            //String rank = "";
            // jLabel2.setText("");
            rankArea.setText("");
            ArrayList<Jugador> jug = control.getRanking();
            for (int i = 0; i < jug.size(); i++) {
                rankArea.append(jug.get(i).toString());
                //rank += jug.get(i).toString();
            }
            //jLabel2.setText(rank);
        } catch (SQLException ex) {
            Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rankingLabelMouseClicked

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ranking.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void salirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseClicked
        // TODO add your handling code here:
        
        int yesNoResponse = JOptionPane.showConfirmDialog(null, "Deseas salir de la aplicación?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if(yesNoResponse == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Adiós");
            System.exit(0);
        }
    }//GEN-LAST:event_salirLabelMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel instrucciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPanel jugadorRegistrado;
    private javax.swing.JLabel jugarLabel;
    private javax.swing.JLabel jugarLabel1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton login;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel nuevoJugador;
    private javax.swing.JLabel nuevoLabel;
    private javax.swing.JPanel play;
    private javax.swing.JTextArea rankArea;
    private javax.swing.JPanel ranking;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPasswordField registerPassword;
    private javax.swing.JPasswordField registerPassword1;
    private javax.swing.JTextField registerUsername;
    private javax.swing.JTextField registerUsername1;
    private javax.swing.JLabel registradoLabel;
    private javax.swing.JLabel salirLabel;
    private javax.swing.JPanel selectHero;
    private javax.swing.JLabel uNInsert;
    private javax.swing.JLabel uNInsert1;
    private javax.swing.JLabel uNInsert2;
    private javax.swing.JLabel uNInsert3;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
