/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Jugador;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import manejadores.JuegoControl;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Fer
 */
public class Juego extends javax.swing.JFrame {

    private JuegoControl control = new JuegoControl();
    private CardLayout card;
    private boolean registerFlag = false;
    private boolean playerClickFlag;

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jugarLabel = new javax.swing.JLabel();
        registradoLabel = new javax.swing.JLabel();
        nuevoLabel = new javax.swing.JLabel();
        rankingLabel = new javax.swing.JLabel();
        salirLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jugarLabel1 = new javax.swing.JLabel();
        play = new javax.swing.JPanel();
        nuevoJugador = new javax.swing.JPanel();
        uNInsert = new javax.swing.JLabel();
        uNInsert1 = new javax.swing.JLabel();
        registerUsername = new javax.swing.JTextField();
        registerPassword = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        selectHero = new javax.swing.JPanel();
        hero4Button = new javax.swing.JToggleButton();
        hero1Button = new javax.swing.JToggleButton();
        hero2Button = new javax.swing.JToggleButton();
        hero3Button = new javax.swing.JToggleButton();
        playButton = new javax.swing.JButton();
        jugadorRegistrado = new javax.swing.JPanel();
        uNInsert2 = new javax.swing.JLabel();
        registerUsername1 = new javax.swing.JTextField();
        uNInsert3 = new javax.swing.JLabel();
        registerPassword1 = new javax.swing.JPasswordField();
        registeredClean = new javax.swing.JButton();
        login = new javax.swing.JButton();
        registeredBack = new javax.swing.JButton();
        ranking = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rankingPlayer1Name = new javax.swing.JLabel();
        rankingPlayer1Won = new javax.swing.JLabel();
        rankingPlayer1Lost = new javax.swing.JLabel();
        rankingPlayer2Name = new javax.swing.JLabel();
        rankingPlayer3Name = new javax.swing.JLabel();
        rankingPlayer4Name = new javax.swing.JLabel();
        rankingPlayer5Name = new javax.swing.JLabel();
        rankingPlayer2Won = new javax.swing.JLabel();
        rankingPlayer3Won = new javax.swing.JLabel();
        rankingPlayer4Won = new javax.swing.JLabel();
        rankingPlayer5Won = new javax.swing.JLabel();
        rankingPlayer2Lost = new javax.swing.JLabel();
        rankingPlayer3Lost = new javax.swing.JLabel();
        rankingPlayer4Lost = new javax.swing.JLabel();
        rankingPlayer5Lost = new javax.swing.JLabel();
        instrucciones = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUPER BATTLE HEROES 2ND ANNIVERSARY GOLD EDITION WITH DLC");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        menu.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Channel", 0, 18)); // NOI18N
        jLabel1.setText("Super Battle Heroes 2nd Anniversary Gold Edition with DLC");

        jugarLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jugarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarLabel.setText("Jugar");
        jugarLabel.setAlignmentX(400.0F);
        jugarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugarLabelMouseClicked(evt);
            }
        });

        registradoLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        registradoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registradoLabel.setText("Jugador Registrado");
        registradoLabel.setAlignmentX(400.0F);
        registradoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registradoLabelMouseClicked(evt);
            }
        });

        nuevoLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        nuevoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoLabel.setText("Nuevo Jugador");
        nuevoLabel.setAlignmentX(400.0F);
        nuevoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoLabelMouseClicked(evt);
            }
        });

        rankingLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        rankingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rankingLabel.setText("Ranking");
        rankingLabel.setAlignmentX(400.0F);
        rankingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankingLabelMouseClicked(evt);
            }
        });

        salirLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        salirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirLabel.setText("Salir");
        salirLabel.setAlignmentX(400.0F);
        salirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirLabelMouseClicked(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText(" ");
        welcomeLabel.setAlignmentX(400.0F);

        jugarLabel1.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jugarLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarLabel1.setText("Instrucciones");
        jugarLabel1.setAlignmentX(400.0F);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(welcomeLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugarLabel1)
                    .addComponent(nuevoLabel)
                    .addComponent(rankingLabel)
                    .addComponent(salirLabel)
                    .addComponent(registradoLabel)
                    .addComponent(jugarLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel)
                .addGap(41, 41, 41)
                .addComponent(jugarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jugarLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registradoLabel)
                .addGap(18, 18, 18)
                .addComponent(nuevoLabel)
                .addGap(18, 18, 18)
                .addComponent(rankingLabel)
                .addGap(18, 18, 18)
                .addComponent(salirLabel)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jPanel1.add(menu, "menu");

        javax.swing.GroupLayout playLayout = new javax.swing.GroupLayout(play);
        play.setLayout(playLayout);
        playLayout.setHorizontalGroup(
            playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        playLayout.setVerticalGroup(
            playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(play, "play");

        uNInsert.setFont(new java.awt.Font("Channel", 0, 14)); // NOI18N
        uNInsert.setText("Contraseña");

        uNInsert1.setFont(new java.awt.Font("Channel", 0, 14)); // NOI18N
        uNInsert1.setText("Nombre de Usuario");

        registerButton.setText("Registrar");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        limpiarButton.setText("Limpiar");
        limpiarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nuevoJugadorLayout = new javax.swing.GroupLayout(nuevoJugador);
        nuevoJugador.setLayout(nuevoJugadorLayout);
        nuevoJugadorLayout.setHorizontalGroup(
            nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoJugadorLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uNInsert)
                    .addComponent(uNInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(registerPassword))
                .addGap(320, 320, 320))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limpiarButton)
                .addGap(59, 59, 59)
                .addComponent(registerButton)
                .addGap(405, 405, 405))
        );
        nuevoJugadorLayout.setVerticalGroup(
            nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoJugadorLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uNInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(nuevoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(limpiarButton))
                .addContainerGap(355, Short.MAX_VALUE))
        );

        jPanel1.add(nuevoJugador, "nuevoJugador");

        hero4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/selection/kyousuke.jpg"))); // NOI18N
        hero4Button.setToolTipText("");
        hero4Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hero4ButtonMouseClicked(evt);
            }
        });

        hero1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/selection/kirito.png"))); // NOI18N
        hero1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hero1ButtonMouseClicked(evt);
            }
        });
        hero1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1ButtonActionPerformed(evt);
            }
        });

        hero2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/selection/koyomi.jpg"))); // NOI18N
        hero2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hero2ButtonMouseClicked(evt);
            }
        });

        hero3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/selection/osomatsu.jpg"))); // NOI18N
        hero3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hero3ButtonMouseClicked(evt);
            }
        });

        playButton.setText("Jugar");
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout selectHeroLayout = new javax.swing.GroupLayout(selectHero);
        selectHero.setLayout(selectHeroLayout);
        selectHeroLayout.setHorizontalGroup(
            selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectHeroLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hero1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hero2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectHeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playButton)
                .addGap(416, 416, 416))
        );
        selectHeroLayout.setVerticalGroup(
            selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectHeroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hero1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(selectHeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hero3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(playButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(selectHero, "selectHero");

        uNInsert2.setFont(new java.awt.Font("Channel", 0, 14)); // NOI18N
        uNInsert2.setText("Nombre de Usuario");

        registerUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUsername1ActionPerformed(evt);
            }
        });

        uNInsert3.setFont(new java.awt.Font("Channel", 0, 14)); // NOI18N
        uNInsert3.setText("Contraseña");

        registeredClean.setText("Limpiar");
        registeredClean.setName("registeredClean"); // NOI18N
        registeredClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registeredCleanMouseClicked(evt);
            }
        });

        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        registeredBack.setText("Atrás");
        registeredBack.setName("registeredBack"); // NOI18N
        registeredBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registeredBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jugadorRegistradoLayout = new javax.swing.GroupLayout(jugadorRegistrado);
        jugadorRegistrado.setLayout(jugadorRegistradoLayout);
        jugadorRegistradoLayout.setHorizontalGroup(
            jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jugadorRegistradoLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uNInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jugadorRegistradoLayout.createSequentialGroup()
                        .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registeredBack)
                            .addComponent(uNInsert3))
                        .addGap(26, 26, 26)
                        .addComponent(registeredClean)))
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jugadorRegistradoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerUsername1)
                            .addComponent(registerPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(259, 259, 259))
                    .addGroup(jugadorRegistradoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(login)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jugadorRegistradoLayout.setVerticalGroup(
            jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jugadorRegistradoLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uNInsert3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jugadorRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registeredClean)
                    .addComponent(login)
                    .addComponent(registeredBack))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jPanel1.add(jugadorRegistrado, "jugadorRegistrado");

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Jugador");

        jLabel3.setText("Juegos Ganados");

        jLabel4.setText("Juegos Perdidos");

        rankingPlayer1Name.setText("player1Name");

        rankingPlayer1Won.setText("Player1Won");

        rankingPlayer1Lost.setText("jLabel5");

        rankingPlayer2Name.setText("jLabel5");

        rankingPlayer3Name.setText("jLabel6");

        rankingPlayer4Name.setText("jLabel7");

        rankingPlayer5Name.setText("jLabel8");

        rankingPlayer2Won.setText("jLabel9");

        rankingPlayer3Won.setText("jLabel10");

        rankingPlayer4Won.setText("jLabel11");

        rankingPlayer5Won.setText("jLabel12");

        rankingPlayer2Lost.setText("jLabel13");

        rankingPlayer3Lost.setText("jLabel6");

        rankingPlayer4Lost.setText("jLabel7");

        rankingPlayer5Lost.setText("jLabel8");

        javax.swing.GroupLayout rankingLayout = new javax.swing.GroupLayout(ranking);
        ranking.setLayout(rankingLayout);
        rankingLayout.setHorizontalGroup(
            rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rankingLayout.createSequentialGroup()
                .addContainerGap(837, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(54, 54, 54))
            .addGroup(rankingLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rankingPlayer1Name)
                    .addGroup(rankingLayout.createSequentialGroup()
                        .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(rankingLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(24, 24, 24))
                                .addComponent(rankingPlayer3Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rankingPlayer4Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rankingPlayer5Name, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(rankingPlayer2Name))
                        .addGap(125, 125, 125)
                        .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rankingPlayer2Won)
                            .addComponent(rankingPlayer1Won)
                            .addComponent(jLabel3)
                            .addComponent(rankingPlayer4Won)
                            .addComponent(rankingPlayer3Won)
                            .addComponent(rankingPlayer5Won))))
                .addGap(121, 121, 121)
                .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rankingPlayer2Lost)
                    .addComponent(jLabel4)
                    .addComponent(rankingPlayer3Lost)
                    .addComponent(rankingPlayer4Lost)
                    .addComponent(rankingPlayer5Lost)
                    .addComponent(rankingPlayer1Lost))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rankingLayout.setVerticalGroup(
            rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rankingLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rankingPlayer1Won)
                    .addComponent(rankingPlayer1Name)
                    .addComponent(rankingPlayer1Lost))
                .addGap(36, 36, 36)
                .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rankingPlayer2Name)
                    .addComponent(rankingPlayer2Won)
                    .addComponent(rankingPlayer2Lost))
                .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rankingLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(rankingPlayer3Lost))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rankingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rankingPlayer3Name)
                            .addComponent(rankingPlayer3Won))))
                .addGap(28, 28, 28)
                .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rankingPlayer4Won)
                    .addComponent(rankingPlayer4Lost)
                    .addComponent(rankingPlayer4Name))
                .addGap(30, 30, 30)
                .addGroup(rankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rankingPlayer5Name)
                    .addComponent(rankingPlayer5Won)
                    .addComponent(rankingPlayer5Lost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(65, 65, 65))
        );

        jPanel1.add(ranking, "ranking");

        javax.swing.GroupLayout instruccionesLayout = new javax.swing.GroupLayout(instrucciones);
        instrucciones.setLayout(instruccionesLayout);
        instruccionesLayout.setHorizontalGroup(
            instruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        instruccionesLayout.setVerticalGroup(
            instruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(instrucciones, "instrucciones");

        getContentPane().add(jPanel1, "card9");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem1.setMnemonic('P');
        jMenuItem1.setText("Pantalla Completa");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registradoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registradoLabelMouseClicked
        // TODO add your handling code here:
        card = (CardLayout) jPanel1.getLayout();
        card.show(jPanel1, "jugadorRegistrado");
    }//GEN-LAST:event_registradoLabelMouseClicked


    private void nuevoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoLabelMouseClicked
        // TODO add your handling code here:
        card = (CardLayout) jPanel1.getLayout();
        card.show(jPanel1, "nuevoJugador");
    }//GEN-LAST:event_nuevoLabelMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
        card = (CardLayout) jPanel1.getLayout();

        int yesNoResponse = JOptionPane.showConfirmDialog(null, "Deseas registrarte?", "Confirmar", JOptionPane.YES_NO_OPTION
        );
        if (yesNoResponse == JOptionPane.YES_OPTION) {
            control.registerUser(registerUsername.getText(), registerPassword.getText());
            welcomeLabel.setText("Bienvenido " + registerUsername.getText());
            registerFlag = true;
            card.show(jPanel1, "menu");
        } else {
            registerFlag = false;
            card.show(jPanel1, "menu");
        }


    }//GEN-LAST:event_registerButtonMouseClicked

    private void limpiarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarButtonMouseClicked
        // TODO add your handling code here:
        registerUsername.setText("");
        registerPassword.setText("");
    }//GEN-LAST:event_limpiarButtonMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        card = (CardLayout) jPanel1.getLayout();
        int yesNoResponse = JOptionPane.showConfirmDialog(null, "Deseas iniciar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION
        );
        if (yesNoResponse == JOptionPane.YES_OPTION) {
            try {
                control.getRegisteredUser(registerUsername1.getText(), registerPassword1.getText());
            } catch (SQLException ex) {
                Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
                registerFlag = false;
            }
            registerFlag = true;
            welcomeLabel.setText("Bienvenido " + control.getP1().getNombre()); //is this ok?
            card.show(jPanel1, "menu");
        } else {
            card.show(jPanel1, "menu");
        }
        registerPassword.setText(" ");
        registerUsername1.setText(" ");
    }//GEN-LAST:event_loginMouseClicked

    private void rankingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankingLabelMouseClicked
        card = (CardLayout) jPanel1.getLayout();
        card.show(jPanel1, "ranking");
        try {
            // TODO add your handling code here:
            //String rank = "";
            // jLabel2.setText("");
            // rankArea.setText("");
            ArrayList<Jugador> jug = control.getRanking();
////            for (int i = 0; i < jug.size(); i++) {
            // rankArea.append(jug.get(i).toString());
            //rank += jug.get(i).toString();
//            }
            //jLabel2.setText(rank);

            // <editor-fold defaultstate="collapsed" desc="Asignar Texto a los Labels"> 
            rankingPlayer1Name.setText(jug.get(0).getNombre());
            rankingPlayer1Won.setText(jug.get(0).getGanados() + "");
            rankingPlayer1Lost.setText(jug.get(0).getJugados() - jug.get(0).getGanados() + "");

            rankingPlayer2Name.setText(jug.get(1).getNombre());
            rankingPlayer2Won.setText(jug.get(1).getGanados() + "");
            rankingPlayer2Lost.setText(jug.get(1).getJugados() - jug.get(1).getGanados() + "");

            rankingPlayer3Name.setText(jug.get(2).getNombre());
            rankingPlayer3Won.setText(jug.get(2).getGanados() + "");
            rankingPlayer3Lost.setText(jug.get(2).getJugados() - jug.get(2).getGanados() + "");

            rankingPlayer4Name.setText(jug.get(3).getNombre());
            rankingPlayer4Won.setText(jug.get(3).getGanados() + "");
            rankingPlayer4Lost.setText(jug.get(3).getJugados() - jug.get(3).getGanados() + "");

            rankingPlayer5Name.setText(jug.get(4).getNombre());
           rankingPlayer5Won.setText(jug.get(4).getGanados()+"");
           rankingPlayer5Lost.setText(jug.get(4).getJugados()-jug.get(4).getGanados()+"");
            // </editor-fold>
        } catch (SQLException ex) {
            Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rankingLabelMouseClicked

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        card = (CardLayout) jPanel1.getLayout();
        registerPassword.setText(" ");
        registerUsername1.setText(" ");
        card.show(jPanel1, "menu");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void salirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseClicked
        // TODO add your handling code here:

        int yesNoResponse = JOptionPane.showConfirmDialog(null, "Deseas salir de la aplicación?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (yesNoResponse == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_salirLabelMouseClicked

    private void registerUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUsername1ActionPerformed

    private void registeredBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registeredBackMouseClicked
        // TODO add your handling code here:
        card = (CardLayout) jPanel1.getLayout();
        card.show(jPanel1, "menu");
    }//GEN-LAST:event_registeredBackMouseClicked

    private void registeredCleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registeredCleanMouseClicked
        // TODO add your handling code here:
        registerPassword.setText(" ");
        registerUsername1.setText(" ");
    }//GEN-LAST:event_registeredCleanMouseClicked

    private void jugarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarLabelMouseClicked
        // TODO add your handling code here:
        int AIselectedHero = 0;
        if (registerFlag == true) {
            card = (CardLayout) jPanel1.getLayout();
            card.show(jPanel1, "selectHero");
            try {
                control.playAgainstAi(); //se agarra AI por default, se puede cambiar para permitir jugar entre dos personas.
                //permitimos que AI escoga primero el heroe
                AIselectedHero = control.selectHero(2, 0);
                switch (AIselectedHero) {
                    case 1:
                        playerClickFlag = false;//bandera para saber de donde proviene el click
                        hero1Button.doClick();
                        playerClickFlag = true;
                        hero1Button.setEnabled(false); //deshabilitamos el boton para que el jugador tenga que escoger un heroe distinto a la AI
                        break;
                    case 2:
                        playerClickFlag = false;
                        hero2Button.doClick();
                        playerClickFlag = true;
                        hero2Button.setEnabled(false);
                        break;
                    case 3:
                        playerClickFlag = false;
                        hero3Button.doClick();
                        playerClickFlag = true;
                        hero3Button.setEnabled(false);
                        break;
                    case 4:
                        playerClickFlag = false;
                        hero4Button.doClick();
                        playerClickFlag = true;
                        hero4Button.setEnabled(false);
                        break;
                    default:
                        playerClickFlag = false;
                        hero1Button.doClick();
                        playerClickFlag = true;
                        hero1Button.setEnabled(false);
                        break;
                }
            } catch (SQLException ex) {

            }

        }
    }//GEN-LAST:event_jugarLabelMouseClicked

    private void hero1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hero1ButtonMouseClicked
        // TODO add your handling code here:
        if (playerClickFlag == true) {
            control.selectHero(1, 1);
        }
    }//GEN-LAST:event_hero1ButtonMouseClicked

    private void hero2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hero2ButtonMouseClicked
        // TODO add your handling code here:
        if (playerClickFlag == true) {
            control.selectHero(1, 2);
        }
    }//GEN-LAST:event_hero2ButtonMouseClicked

    private void hero3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hero3ButtonMouseClicked
        // TODO add your handling code here:
        if (playerClickFlag == true) {
            control.selectHero(1, 3);
        }
    }//GEN-LAST:event_hero3ButtonMouseClicked

    private void hero4ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hero4ButtonMouseClicked
        // TODO add your handling code here:
        if (playerClickFlag == true) {
            control.selectHero(1, 4);
        }
    }//GEN-LAST:event_hero4ButtonMouseClicked

    private void hero1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1ButtonActionPerformed

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        // TODO add your handling code here:
        card = (CardLayout) jPanel1.getLayout();
        card.show(jPanel1, "play");
    }//GEN-LAST:event_playButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton hero1Button;
    private javax.swing.JToggleButton hero2Button;
    private javax.swing.JToggleButton hero3Button;
    private javax.swing.JToggleButton hero4Button;
    private javax.swing.JPanel instrucciones;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jugadorRegistrado;
    private javax.swing.JLabel jugarLabel;
    private javax.swing.JLabel jugarLabel1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton login;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel nuevoJugador;
    private javax.swing.JLabel nuevoLabel;
    private javax.swing.JPanel play;
    private javax.swing.JButton playButton;
    private javax.swing.JPanel ranking;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JLabel rankingPlayer1Lost;
    private javax.swing.JLabel rankingPlayer1Name;
    private javax.swing.JLabel rankingPlayer1Won;
    private javax.swing.JLabel rankingPlayer2Lost;
    private javax.swing.JLabel rankingPlayer2Name;
    private javax.swing.JLabel rankingPlayer2Won;
    private javax.swing.JLabel rankingPlayer3Lost;
    private javax.swing.JLabel rankingPlayer3Name;
    private javax.swing.JLabel rankingPlayer3Won;
    private javax.swing.JLabel rankingPlayer4Lost;
    private javax.swing.JLabel rankingPlayer4Name;
    private javax.swing.JLabel rankingPlayer4Won;
    private javax.swing.JLabel rankingPlayer5Lost;
    private javax.swing.JLabel rankingPlayer5Name;
    private javax.swing.JLabel rankingPlayer5Won;
    private javax.swing.JButton registerButton;
    private javax.swing.JPasswordField registerPassword;
    private javax.swing.JPasswordField registerPassword1;
    private javax.swing.JTextField registerUsername;
    private javax.swing.JTextField registerUsername1;
    private javax.swing.JButton registeredBack;
    private javax.swing.JButton registeredClean;
    private javax.swing.JLabel registradoLabel;
    private javax.swing.JLabel salirLabel;
    private javax.swing.JPanel selectHero;
    private javax.swing.JLabel uNInsert;
    private javax.swing.JLabel uNInsert1;
    private javax.swing.JLabel uNInsert2;
    private javax.swing.JLabel uNInsert3;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
